### ISSUE TITLE
Undergrounds are not showing up

### ISSUE THREAD

**Issue by henry4711lp** [Defjam121/MMM-VrrApp#1]
I have put the same station in the config file that has S trains an undergrounds but only the Trains are showing up.
Config:
  {
                module: 'MMM-DBF',
            position: 'top_right',
            config: {
                showApp: false,
                station: "Düsseldorf-Oberbilk",
                height:"600px",
                width:"400px",
                timeOption: "time+countdown",
                train: "S1",
                }
        },

**Comment by Helpi90** [comment]
I have tested your config on my system. Only the S1 is displayed. Is that what you wanted?  Underground trains dont work with that module. Use [MMM-VRR](https://github.com/Helpi90/MMM-Vrr) if you need them.
